"use client";
import { useEffect, useMemo, useState } from "react";
import { collection, deleteDoc, doc, onSnapshot, orderBy, query, setDoc } from "firebase/firestore";
import { onAuthStateChanged, signInWithPopup, signOut, type User } from "firebase/auth";
import { deleteObject, getDownloadURL, ref, uploadString } from "firebase/storage";
import { AnimatePresence, motion } from "framer-motion";
import { BookOpen, Check, ChevronLeft, Cloud, GraduationCap, LogIn, Plus, Sparkles, Trash2, X } from "lucide-react";
import { auth, db, firebaseReady, googleProvider, storage } from "@/lib/firebase";
import type { Flashcard, Side, StudyMode } from "@/lib/types";
import { DrawCanvas } from "@/components/DrawCanvas";
import { Flashcard as Card } from "@/components/Flashcard";
import { playSound } from "@/lib/sounds";

const seed: Flashcard[] = [{id:"welcome",deck:"เริ่มต้น",tags:["demo"],front:{text:"Hello"},back:{text:"สวัสดี"},createdAt:1},{id:"learn",deck:"เริ่มต้น",tags:["demo"],front:{text:"Thank you"},back:{text:"ขอบคุณ"},createdAt:2},{id:"play",deck:"เริ่มต้น",tags:["demo"],front:{text:"Apple"},back:{text:"แอปเปิล"},createdAt:3},{id:"good",deck:"เริ่มต้น",tags:["demo"],front:{text:"Good morning"},back:{text:"อรุณสวัสดิ์"},createdAt:4}];
const emptySide: Side = { text: "" };
function label(s:Side) { return s.text || (s.drawing ? "ภาพวาด" : "—"); }

export default function Home() {
 const [user,setUser]=useState<User|null>(null), [cards,setCards]=useState<Flashcard[]>(seed), [screen,setScreen]=useState<"home"|"create"|"select"|"study"|"result">("home"), [front,setFront]=useState<Side>(emptySide),[back,setBack]=useState<Side>(emptySide),[deck,setDeck]=useState("ทั่วไป"),[tags,setTags]=useState(""),[drawingSide,setDrawingSide]=useState<"front"|"back"|null>(null),[selected,setSelected]=useState<string[]>(seed.map(c=>c.id)),[mode,setMode]=useState<StudyMode>("flip"),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[score,setScore]=useState({known:0,correct:0,answered:0}),[answer,setAnswer]=useState<string|undefined>(),[toast,setToast]=useState("");
 useEffect(()=>{ const activeAuth=auth,activeDb=db;if(!activeAuth||!activeDb)return; const unsubAuth=onAuthStateChanged(activeAuth,setUser); let stop=()=>{}; const unsub=onAuthStateChanged(activeAuth,u=>{stop();if(u)stop=onSnapshot(query(collection(activeDb,"users",u.uid,"cards"),orderBy("createdAt","desc")),s=>setCards(s.docs.map(d=>d.data() as Flashcard)));});return()=>{unsubAuth();unsub();stop();};},[]);
 const pool=useMemo(()=>cards.filter(c=>selected.includes(c.id)),[cards,selected]); const current=pool[index%Math.max(pool.length,1)];
 const options=useMemo(()=>{if(!current)return[]; const other=pool.filter(c=>c.id!==current.id).map(c=>label(c.back)); const unique=[...new Set(other)].slice(0,3); while(unique.length<3)unique.push(`ตัวเลือก ${unique.length+1}`); return [label(current.back),...unique].sort(()=>Math.random()-.5);},[current?.id,index,pool]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const login=async()=>{if(!auth||!firebaseReady)return notify("เพิ่ม Firebase keys ใน .env.local ก่อน"); try{await signInWithPopup(auth,googleProvider!)}catch{notify("เข้าสู่ระบบไม่สำเร็จ")}};
 const uploadDrawing=async(side:Side,cardId:string,position:"front"|"back"):Promise<Side>=>{if(!side.drawing||!user||!storage)return side;const drawingPath=`users/${user.uid}/drawings/${cardId}-${position}.webp`;const fileRef=ref(storage,drawingPath);await uploadString(fileRef,side.drawing,"data_url");return {...side,drawing:await getDownloadURL(fileRef),drawingPath};};
 const save=async()=>{if(!front.text&&!front.drawing||!back.text&&!back.drawing)return notify("ใส่ข้อมูลทั้งด้านหน้าและด้านหลังก่อน");const id=crypto.randomUUID();try{const savedFront=await uploadDrawing(front,id,"front");const savedBack=await uploadDrawing(back,id,"back");const card:Flashcard={id,deck,tags:tags.split(",").map(x=>x.trim()).filter(Boolean),front:savedFront,back:savedBack,createdAt:Date.now()};if(user&&db)await setDoc(doc(db,"users",user.uid,"cards",card.id),card);else setCards(a=>[card,...a]);setSelected(a=>[...a,card.id]);setFront(emptySide);setBack(emptySide);setScreen("home");notify(user?"บันทึกและซิงก์การ์ดแล้ว":"บันทึกการ์ดแล้ว");}catch(error){console.error(error);notify("อัปโหลดภาพไม่สำเร็จ — ตรวจ Firebase Storage และ rules");}};
 const removeCard=async(card:Flashcard)=>{if(!window.confirm(`ลบการ์ด “${label(card.front)}” ใช่ไหม?`))return;try{const activeStorage=storage;if(user&&db){await deleteDoc(doc(db,"users",user.uid,"cards",card.id));if(activeStorage){await Promise.all([card.front.drawingPath,card.back.drawingPath].filter(Boolean).map(path=>deleteObject(ref(activeStorage,path!)).catch(()=>undefined)));}}else setCards(all=>all.filter(item=>item.id!==card.id));setSelected(all=>all.filter(id=>id!==card.id));notify("ลบการ์ดแล้ว");}catch(error){console.error(error);notify("ลบการ์ดไม่สำเร็จ");}};
 const next=(known?:boolean)=>{if(known!==undefined)setScore(s=>({...s,known:s.known+(known?1:0)}));setFlipped(false);setAnswer(undefined);if(index+1>=pool.length){setScreen("result")}else setIndex(i=>i+1);};
 const choose=(v:string)=>{if(answer)return;setAnswer(v);const ok=v===label(current.back);playSound(ok?"correct":"wrong");setScore(s=>({...s,answered:s.answered+1,correct:s.correct+(ok?1:0)}));setTimeout(()=>next(),900)};
 const begin=()=>{if(!pool.length)return notify("เลือกการ์ดอย่างน้อย 1 ใบ");setIndex(0);setScore({known:0,correct:0,answered:0});setScreen("study")};
 const updateDrawing=(im:string)=>drawingSide==="front"?setFront(a=>({...a,drawing:im,text:""})):setBack(a=>({...a,drawing:im,text:""}));
 if(screen==="create")return <main className="mx-auto max-w-3xl p-5 pb-12"><Top back={()=>setScreen("home")}/><h1 className="mt-8 text-3xl font-bold">สร้างการ์ดใหม่</h1><p className="mt-1 text-slate-500">เลือกพิมพ์ หรือวาดลงบนการ์ดแต่ละด้าน</p><div className="mt-7 grid gap-5 md:grid-cols-2">{(["front","back"] as const).map(side=>{const value=side==="front"?front:back;const setter=side==="front"?setFront:setBack;return <section key={side} className="glass rounded-[2rem] p-5"><h2 className="font-bold">ด้าน{side==="front"?"หน้า — คำถาม":"หลัง — คำตอบ"}</h2><div className="mt-4 flex gap-2"><button onClick={()=>setDrawingSide(null)} className="rounded-xl bg-violet-100 px-3 py-2 text-sm text-violet-700">ข้อความ</button><button onClick={()=>setDrawingSide(side)} className="rounded-xl bg-violet-100 px-3 py-2 text-sm text-violet-700">วาดภาพ</button></div>{drawingSide===side?<div className="mt-3"><DrawCanvas value={value.drawing} onChange={updateDrawing}/></div>:<textarea value={value.text||""} onChange={e=>setter({text:e.target.value})} placeholder={side==="front"?"เช่น Serendipity":"เช่น ความบังเอิญที่งดงาม"} className="mt-3 h-36 w-full resize-none rounded-2xl border border-violet-100 bg-white p-4 outline-none focus:ring-2 focus:ring-violet-300"/>}</section>})}</div><section className="mt-5 glass grid gap-3 rounded-[2rem] p-5 md:grid-cols-2"><input value={deck} onChange={e=>setDeck(e.target.value)} placeholder="ชื่อ Deck" className="rounded-xl border p-3"/><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Tags คั่นด้วย ," className="rounded-xl border p-3"/></section><button onClick={save} className="mt-5 w-full rounded-2xl bg-ink py-4 font-bold text-white">บันทึกการ์ด</button></main>;
 if(screen==="select")return <main className="mx-auto max-w-2xl p-5"><Top back={()=>setScreen("home")}/><h1 className="mt-8 text-3xl font-bold">เตรียม Session</h1><p className="mt-1 text-slate-500">เลือกการ์ดที่ต้องการฝึก แล้วเลือกรูปแบบ</p><div className="mt-6 space-y-3">{cards.map(c=><label key={c.id} className="glass flex cursor-pointer items-center gap-4 rounded-2xl p-4"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(s=>s.includes(c.id)?s.filter(id=>id!==c.id):[...s,c.id])} className="h-5 w-5 accent-violet-600"/><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-600"><BookOpen size={19}/></span><span className="flex-1"><b>{label(c.front)}</b><small className="ml-2 text-slate-400">{c.deck}</small></span></label>)}</div><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setMode("flip")} className={'rounded-2xl p-5 text-left '+(mode==="flip"?"bg-violet-600 text-white":"glass")}><b>Classic Flip</b><span className="mt-1 block text-sm opacity-70">พลิกและประเมินตนเอง</span></button><button onClick={()=>setMode("quiz")} className={'rounded-2xl p-5 text-left '+(mode==="quiz"?"bg-violet-600 text-white":"glass")}><b>Quick Quiz</b><span className="mt-1 block text-sm opacity-70">เลือกคำตอบ 4 ตัวเลือก</span></button></div><button onClick={begin} className="mt-5 w-full rounded-2xl bg-ink py-4 font-bold text-white">เริ่มเรียน {selected.length} ใบ</button></main>;
 if(screen==="study"&&current)return <main className="mx-auto flex min-h-screen max-w-2xl flex-col p-5"><Top back={()=>setScreen("home")}/><div className="mt-8 flex items-center justify-between text-sm font-bold text-slate-400"><span>{mode==="flip"?"CLASSIC FLIP":"QUICK QUIZ"}</span><span>{index+1} / {pool.length}</span></div><div className="mt-5 flex flex-1 flex-col items-center">{mode==="flip"?<><Card front={current.front} back={current.back} flipped={flipped} onFlip={()=>{if(!flipped)playSound("flip");setFlipped(x=>!x)}}/><AnimatePresence>{flipped&&<motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mt-7 grid w-full max-w-xl grid-cols-2 gap-3"><button onClick={()=>next(false)} className="rounded-2xl bg-rose-100 py-4 font-bold text-rose-600">จำไม่ได้</button><button onClick={()=>next(true)} className="rounded-2xl bg-emerald-500 py-4 font-bold text-white">จำได้ <Check className="inline" size={17}/></button></motion.div>}</AnimatePresence></>:<><div className="grid min-h-52 w-full place-items-center rounded-[2rem] bg-white p-8 shadow-float">{current.front.drawing?<img src={current.front.drawing} alt="ภาพวาดคำถาม" className="max-h-64 max-w-full rounded-2xl object-contain"/>:<p className="text-center text-3xl font-bold">{label(current.front)}</p>}</div><div className="mt-6 grid w-full gap-3">{options.map((o,i)=>{const correct=o===label(current.back),chosen=answer===o;let style="bg-white hover:bg-violet-50";if(answer&&(chosen||correct))style=correct?"bg-emerald-500 text-white":"bg-rose-500 text-white";return <button key={i} disabled={!!answer} onClick={()=>choose(o)} className={'rounded-2xl p-4 text-left font-semibold transition '+style}><span className="mr-3 opacity-60">{String.fromCharCode(65+i)}</span>{o}</button>})}</div></>}</div></main>;
 if(screen==="result")return <main className="grid min-h-screen place-items-center p-5"><section className="glass w-full max-w-md rounded-[2.5rem] p-8 text-center shadow-float"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-amber-100 text-amber-500"><Sparkles/></div><h1 className="mt-5 text-3xl font-bold">Session สำเร็จ!</h1><p className="mt-2 text-slate-500">คุณทำได้ยอดเยี่ยม มาฝึกต่อให้เก่งขึ้นกัน</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-violet-50 p-4"><b className="text-2xl text-violet-600">{mode==="flip"?score.known:score.correct}</b><span className="block text-sm text-slate-500">{mode==="flip"?"จำได้":"ตอบถูก"}</span></div><div className="rounded-2xl bg-violet-50 p-4"><b className="text-2xl text-violet-600">{pool.length}</b><span className="block text-sm text-slate-500">การ์ดทั้งหมด</span></div></div><button onClick={()=>setScreen("select")} className="mt-6 w-full rounded-2xl bg-ink py-4 font-bold text-white">ฝึกอีกครั้ง</button></section></main>;
 return <main className="mx-auto min-h-screen max-w-5xl p-5 pb-12"><header className="flex items-center justify-between"><div className="flex items-center gap-2 text-xl font-black tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-600 text-white"><GraduationCap/></span>flipit</div>{user?<button onClick={()=>signOut(auth!)} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm"><img className="h-6 w-6 rounded-full" src={user.photoURL||""}/>{user.displayName?.split(" ")[0]}</button>:<button onClick={login} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm"><LogIn size={16}/> Google</button>}</header><section className="mt-8 overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-violet-600 via-indigo-600 to-violet-500 p-8 text-white sm:p-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-violet-200">Your gentle study space</p><h1 className="mt-3 max-w-xl text-4xl font-bold leading-tight sm:text-5xl">เรียนรู้ทีละใบ<br/>จำได้อย่างยาวนาน</h1><p className="mt-4 max-w-md text-violet-100">สร้างแฟลชการ์ดจากข้อความหรือปลายนิ้ว แล้วเปลี่ยนเวลาว่างให้เป็นช่วงเวลาที่มีความหมาย</p><div className="mt-7 flex gap-3"><button onClick={()=>setScreen("create")} className="flex items-center gap-2 rounded-2xl bg-white px-5 py-3 font-bold text-violet-700"><Plus size={18}/> สร้างการ์ด</button><button onClick={()=>setScreen("select")} className="rounded-2xl border border-white/30 px-5 py-3 font-bold">เริ่มเรียน</button></div></section><section className="mt-8"><div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold">คลังการ์ด</h2><p className="mt-1 text-slate-500">{cards.length} การ์ด พร้อมเรียนรู้</p></div><span className="flex items-center gap-1 text-sm text-slate-400"><Cloud size={15}/>{user?"Sync แล้ว":"เก็บในเครื่อง"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(c=><article key={c.id} className="glass relative rounded-3xl p-5"><button onClick={()=>removeCard(c)} aria-label={`ลบการ์ด ${label(c.front)}`} className="absolute right-4 top-4 rounded-xl p-2 text-slate-400 transition hover:bg-rose-50 hover:text-rose-500"><Trash2 size={17}/></button><span className="rounded-lg bg-violet-100 px-2 py-1 text-xs font-bold text-violet-600">{c.deck}</span><h3 className="mt-5 text-xl font-bold">{label(c.front)}</h3><p className="mt-1 text-slate-400">{label(c.back)}</p><div className="mt-5 flex gap-1">{c.tags.map(t=><span key={t} className="text-xs text-slate-400">#{t}</span>)}</div></article>)}</div></section>{toast&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-2xl bg-ink px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}</main>;
}
function Top({back}:{back:()=>void}){return <button onClick={back} className="flex items-center gap-1 rounded-xl bg-white px-3 py-2 text-sm font-semibold shadow-sm"><ChevronLeft size={17}/> กลับ</button>}
