"use client";
import { useEffect, useRef, useState } from "react";
import { Eraser, RotateCcw, Trash2 } from "lucide-react";

export function DrawCanvas({ value, onChange }: { value?: string; onChange: (image: string) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const [color, setColor] = useState("#3b3655"); const [size, setSize] = useState(5); const [eraser, setEraser] = useState(false); const history = useRef<ImageData[]>([]);
  const ctx = () => canvasRef.current?.getContext("2d");
  useEffect(() => { const c = canvasRef.current, x = ctx(); if (!c || !x) return; x.fillStyle = "#fff"; x.fillRect(0,0,c.width,c.height); if(value) { const im = new Image(); im.onload=()=>x.drawImage(im,0,0,c.width,c.height); im.src=value; } }, []); // initialize once
  const pos = (e: React.PointerEvent<HTMLCanvasElement>) => { const r=e.currentTarget.getBoundingClientRect(); return { x:(e.clientX-r.left)*canvasRef.current!.width/r.width, y:(e.clientY-r.top)*canvasRef.current!.height/r.height }; };
  const save = () => { const c=canvasRef.current; if(!c)return; const optimized=document.createElement("canvas"); optimized.width=360;optimized.height=216; const x=optimized.getContext("2d"); if(!x)return; x.fillStyle="#fff";x.fillRect(0,0,optimized.width,optimized.height);x.drawImage(c,0,0,optimized.width,optimized.height); onChange(optimized.toDataURL("image/webp",.72)); };
  const start = (e: React.PointerEvent<HTMLCanvasElement>) => { e.currentTarget.setPointerCapture(e.pointerId); const x=ctx(); if(!x)return; history.current.push(x.getImageData(0,0,600,360)); drawing.current=true; const p=pos(e); x.beginPath(); x.moveTo(p.x,p.y); };
  const move = (e: React.PointerEvent<HTMLCanvasElement>) => { if(!drawing.current)return; const x=ctx(); if(!x)return; const p=pos(e); x.lineCap="round"; x.lineJoin="round"; x.lineWidth=size; x.strokeStyle=eraser?"#fff":color; x.lineTo(p.x,p.y); x.stroke(); };
  const undo=()=>{const x=ctx(), last=history.current.pop();if(x&&last)x.putImageData(last,0,0);save();}; const clear=()=>{const x=ctx();if(x){history.current.push(x.getImageData(0,0,600,360));x.fillStyle="#fff";x.fillRect(0,0,600,360);save();}};
  return <div className="rounded-3xl border border-violet-100 bg-white p-3"><canvas ref={canvasRef} width="600" height="360" className="h-48 w-full touch-none cursor-crosshair rounded-2xl bg-white" onPointerDown={start} onPointerMove={move} onPointerUp={()=>{drawing.current=false;save();}} onPointerLeave={()=>{if(drawing.current){drawing.current=false;save();}}}/><div className="mt-3 flex flex-wrap items-center gap-2"><div className="flex gap-1">{["#3b3655","#7764c5","#ff7b6b","#f2af42","#4caf82"].map(c=><button aria-label="เลือกสี" key={c} onClick={()=>{setColor(c);setEraser(false)}} className="h-7 w-7 rounded-full border-2 border-white" style={{background:c, outline:color===c&&!eraser?"2px solid #7764c5":undefined}}/>)}</div><input aria-label="ขนาดปากกา" type="range" min="2" max="24" value={size} onChange={e=>setSize(+e.target.value)} className="w-20 accent-violet-500"/><button onClick={()=>setEraser(!eraser)} className={'rounded-xl p-2 '+(eraser?'bg-violet-100 text-violet-700':'bg-slate-100')}><Eraser size={16}/></button><button onClick={undo} className="rounded-xl bg-slate-100 p-2"><RotateCcw size={16}/></button><button onClick={clear} className="rounded-xl bg-rose-50 p-2 text-rose-500"><Trash2 size={16}/></button></div></div>;
}
